### ISSUE TITLE
Python Consol terminated prematurely when the python scripts produce errors

### ISSUE THREAD

**Issue by ngo-lap** [smarie/python-object-as-daemon#14]
Since I am trying to open a Python console visibly for debugging, every time a bug is produced from within Python side, the Python console is terminated, leaving the daemon within Matlab waiting forever. The problem is that the Python console is terminated almost immediately, giving us no time to analyze the errors.  

So far, I have to use a screen recorder to capture the error. I tried improvising by removing the `terminate_daemon` within the source code, but it did not work.

**Comment by smarie** [comment]
Thanks for reporting this! Could you by any chance reproduce this issue outside of matlab ? That would help reproducing it, creating the corresponding test and fixing it.

**Comment by smarie** [comment]
Apparently this came from an unpicklable exception. I will introduce it in the tests and fix.

**Comment by smarie** [comment]
This will shortly be available in 2.1.0 (once travis will have released it). Let me know if it is ok !
